classDiagram  
MojitoTheme --> MojitoColor
MojitoTheme --> MojitoFont
MojitoColor --> CostBreakDownColor
MojitoColor --> DeliveryColor
MojitoColor --> PaymentConfirmationColor
MojitoColor --> CheckoutColor

MojitoColor --> CheckoutColor

class MojitoTheme {
    -MojitoColor color
    -MojitoFont font
}
class MojitoColor {
    -String primary
    -String secondary
    -String background
    -String errorBackground
    -String cardBackground
    -String text
    -String placeholder
    -CheckoutColor checkout
    -CostBreakDownColor delivery
    -PaymentConfirmationColor paymentConfirmation
}
class MojitoFont {
    -String primary
    -String secondary
}
class CheckoutColor {
    -String continueButtonTextColor
    -String continueButtonBackgroundColor
} 
class CostBreakDownColor {
    -String applyButtonBackground
    -String applyButtonTextColor
}
class DeliveryColor {
    -String deliveryButtonTextColor
    -String deliveryButtonBackgroundColor
}
class PaymentConfirmationColor {
    -String processedBackground
    -String processedTextColor
    -String awaitingPaymentBackground
    -String awaitingPaymentTextColor
    -String copyIconColor
}

