classDiagram
MojitoCheckout --> UserInfo
MojitoCheckout --> CheckoutOptions
MojitoCheckout --> MojitoTheme
MojitoCheckout --> MojitoUIConfiguration 
MojitoCheckout --> Events 


class MojitoCheckout{
    -uiConfiguration MojitoUIConfiguration
    -checkoutOptions CheckoutOptions
    -UserInfo userInfo
    -MojitoTheme theme
    -Boolean show
    -Boolean debug
    -Boolean enableSardine
    -String sardineEnvironment
    -Events events
}
class UserInfo {
    -String name
    -String email
}
class MojitoUIConfiguration {
    -BillingUIConfiguration billing
    -PaymentUIConfiguration payment
    -CostBreakdownUIConfiguration costBreakdown
    -PaymentConfirmationUIConfiguration paymentConfirmation
}
class MojitoTheme {
    -MojitoColor color
    -MojitoFont font
}
class CheckoutOptions {
  -String orgId
  -String lotId
  -Number quantity
  -String paymentId
  -String collectionItemId
  -String invoiceId
  -Boolean vertexEnabled
}
class Events {
    -Event onError
    -Event onEvent
    -Event onCatch
}