classDiagram

MojitoUIConfiguration --> GlobalUIConfiguration
MojitoUIConfiguration --> BillingUIConfiguration
MojitoUIConfiguration --> PaymentUIConfiguration
MojitoUIConfiguration --> CostBreakdownUIConfiguration
MojitoUIConfiguration --> DeliveryUIConfiguration
MojitoUIConfiguration --> PaymentConfirmationUIConfiguration

class MojitoUIConfiguration {
    -GlobalUIConfiguration global
    -BillingUIConfiguration billing
    -PaymentUIConfiguration payment
    -CostBreakdownUIConfiguration costBreakdown
    -DeliveryUIConfiguration delivery
    -PaymentConfirmationUIConfiguration paymentConfirmation
}

class GlobalUIConfiguration {
    -String logoSrc
    -String loaderImageSrc
    -String errorImageSrc
}

class BillingUIConfiguration {
    -Boolean isEnableExpressCheckout
    -Boolean gpay
    -Boolean applepay
    -Boolean walletConnect
    -Boolean metaMask
}
class PaymentUIConfiguration {
    -Boolean applepay
    -Boolean gpay
    -Boolean walletConnect
    -Boolean wire
    -Boolean creditCard
}
class CostBreakdownUIConfiguration {
    -Boolean showDiscountCode
}
class PaymentConfirmationUIConfiguration {
    -Boolean showDiscountCode
    -Boolean goToLabel
    -JSXElement wireTransferInstructions
    -JSXElement creditCardInstructions
    -Event onGoTo
}

class DeliveryUIConfiguration {
    -Boolean showConnectWallet
}