classDiagram
class MojitoUIConfiguration {
    -BillingUIConfiguration billing
    -PaymentUIConfiguration payment
    -DeliveryUIConfiguration delivery
    -PaymentConfirmationUIConfiguration paymentConfirmation
}
class BillingUIConfiguration {
    -Boolean isEnableExpressCheckout
}
class PaymentUIConfiguration {
    
}
class DeliveryUIConfiguration {
    
}
class PaymentConfirmationUIConfiguration {
    
}
MojitoUIConfiguration --> BillingUIConfiguration
MojitoUIConfiguration --> PaymentUIConfiguration
MojitoUIConfiguration --> DeliveryUIConfiguration
MojitoUIConfiguration --> PaymentConfirmationUIConfiguration
 