name: "Code Style & Quality"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
        working-directory: ./app
      - run: yarn lint
        working-directory: ./app
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: yarn dist:build
      - run: test -e ./dist/cjs/index.js
      - run: test -e ./dist/esm/index.js

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: '16.x'
  #         registry-url: 'https://registry.npmjs.org'
  #     - run: yarn install --frozen-lockfile
  #       working-directory: ./app
  #     - run: yarn test
  #       working-directory: ./app
